version: "3.8"

services:
    front:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "${WEB_PORT}:3000"
        volumes:
            - ./src:/usr/src/app:ro
        environment:
            - CHOKIDAR_USEPOLLING=true # needed for watching files in windows
        env_file:
            - .env
        restart: on-failure
